import { Product } from './types/Product';

export const sampleProducts: Product[] = [
  {
    name: 'Sample Product',
    slug: 'sample-product',
    image: '../images/p1.jpg',
    category: 'Pants',
    brand: 'Nike',
    price: 100,
    countInStock: 10,
    description: 'Sample Description',
    rating: 5.0,
    numReviews: 14,
  },
  {
    name: 'Sample Product 2',
    slug: 'sample-product-2',
    image: '../images/p2.jpg',
    category: 'Shirts',
    brand: 'Adidas',
    price: 200,
    countInStock: 20,
    description: 'Sample Description',
    rating: 4.0,
    numReviews: 110,
  },
  {
    name: 'Sample Product 3',
    slug: 'sample-product-3',
    image: '../images/p3.jpg',
    category: 'Pants',
    brand: 'Puma',
    price: 300,
    countInStock: 0,
    description: 'Sample Description',
    rating: 3.5,
    numReviews: 140,
  },
  {
    name: 'Sample Product 4',
    slug: 'sample-product-4',
    image: '../images/p4.jpg',
    category: 'Pants',
    brand: 'Nike',
    price: 400,
    countInStock: 15,
    description: 'Sample Description',
    rating: 4.5,
    numReviews: 10,
  },
];
